# Generated by Django 5.2.4 on 2025-08-10 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='component',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='component',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='component',
            name='styles',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='component',
            name='content',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='page',
            name='name',
            field=models.CharField(default='Home', max_length=100),
        ),
        migrations.AlterField(
            model_name='section',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
